import React, { useState, useEffect } from "react";
import Head from "next/head";
import Link from "next/link";
import { GetStaticProps } from "next";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import useSWR from "swr";

type HomeProps = {
  artists: [];
  access_token: string;
};

// const code = new URLSearchParams(window.location.search).get("code");

// const fetcher = async (input: RequestInfo,   init: RequestInit, ...args:
// any[]) => {   const res = await fetch(input, init).then(res => res.json())}

export default function Home(props: HomeProps) {
  // const { artists } = props;
  console.log(props);
  // console.log(code);

  const [spotifyToken, setSpotifyToken] = useState("");
  const [artists, setArtists] = useState("");

  // useEffect(() => {
  //   fetch(
  //     `https://accounts.spotify.com/authorize?client_id=${process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_ID}&redirect_uri=http://localhost:3000&scope=user-top-read%20user-read-recently-played&response_type=token`,
  //     {
  //       method: "GET",
  //     }
  //   ).then((res) => res.text());
  // });

  return (
    <div className="flex flex-col flex-1 min-h-screen">
      <Head>
        <title>Syauqy HomePage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-white">
        {/* {artists.map((artist) => {
          <li>{artist}</li>;
        })} */}
      </div>
    </div>
  );
}

export async function getStaticProps() {
  // const res = await fetch(
  //   `https://accounts.spotify.com/authorize?client_id=${process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_ID}&redirect_uri=http://localhost:3000&scope=user-top-read%20user-read-recently-played&response_type=token`,
  //   {
  //     method: "GET",
  //   }
  // ).then((res) => console.log(res));
  // const access_token = await res.json();
  // const res = await fetch("https://accounts.spotify.com/api/token", {
  //   headers: {
  //     "Content-Type": "application/x-www-form-urlencoded",
  //     Authorization:
  //       `Basic ` +
  //       Buffer.from(
  //         process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_ID +
  //           `:` +
  //           process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET
  //       ).toString("base64"),
  //   },
  //   body: new URLSearchParams({ grant_type: "client_credentials" }),
  //   method: "POST",
  // });
  // const access_token = JSON.parse(res);

  return {
    props: {
      // access_token: res,
      artists: ["eric clapton", "mcr"],
    },
  };
}
