import React, { useEffect } from "react";
import Head from "next/head";
import Link from "next/link";
import SpotifyGetArtist from "~/components/spotify/spotify-get-artist";

const SPOTIFY_AUTH_URL = `https://accounts.spotify.com/authorize?client_id=${process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_ID}&redirect_uri=http://localhost:3000/spotify&scope=user-top-read%20user-read-recently-played&response_type=token`;

const getSpotifyParams = (hash) => {
  const stringAfterHash = hash.substring(1);
  const urlParams = stringAfterHash.split("&");
  const splittedParams = urlParams.reduce((accumulater, currentValue) => {
    const [key, value] = currentValue.split("=");
    accumulater[key] = value;
    return accumulater;
  }, {});
  return splittedParams;
};

export default function Spotify() {
  useEffect(() => {
    if (window.location.hash) {
      const { access_token, expires_in, token_type } = getSpotifyParams(
        window.location.hash
      );
      console.log(access_token);
      localStorage.clear();
      localStorage.setItem("accessToken", access_token);
    }
  }, []);
  return (
    <div className="flex flex-col flex-1 min-h-screen">
      <Head>
        <title>Syauqy Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-white">
        <div className="flex-1 flex">
          <div className="space-y-3">
            <Link href={SPOTIFY_AUTH_URL} passHref>
              <a className="rounded-full py-3 px-6 bg-green-600">
                Login Spotify
              </a>
            </Link>
            <SpotifyGetArtist />
          </div>
        </div>
        {/* {artists.map((artist) => {
          <li>{artist}</li>;
        })} */}
      </div>
    </div>
  );
}
